### ISSUE TITLE
Save Player Game mode when switching

### ISSUE THREAD

**Issue by dmunozv04** [sleepingdragoninn/switchy-inventories#1]
It would be nice to allow to save the current GameMode on the profile. I'll make a PR with this feature.

**Comment by sleepingdragoninn** [comment]
hey hello! this vanilla module is tracked here: https://github.com/sisby-folk/switchy/issues/8

As for where it should go, I'm not entirely sure! it's why we've marked it as ??? 

I know some servers have creative-specific worlds and other bits like that. Considering mixing modes is quite a unique case, It's possible it would work best in an entirely new addon!

**Comment by dmunozv04** [comment]
Thanks for the comment, I hadn't seen that issue before; it's really helpful. I'll move this new module to its own mod, probably called twitchy-vanilla-extras, if you don't have a problem with the mod using the switchy name.

**Comment by sleepingdragoninn** [comment]
where possible, we prefer addon names and summaries to reflect their contents - if you're not looking to cover other modules you think would fit together on first release, Switchy Gamemode would be better!

You're free to use the name as you like, just match the Switchy license. There's nothing wrong with small mods! ^^
